title: SHANG Linlin
logo: /assets/img/logo.png
description: Ph.D. Candidate at Donders Institute for Brain, Cognition, and Behaviour

[Publications](/shangll/shangll.github.io/subpage-1-paper.md)

[Conferences](https://github.com/shangll/shangll.github.io/blob/master/subpage-2-confer.md)

[Blog](https://github.com/shangll/shangll.github.io/blob/master/subpage-3-blog.md)

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
