theme: jekyll-theme-minimal

title: SHANG Linlin
affiliation: Ph.D. Candidate at Donders Institute for Brain, Cognition, and Behaviour
email: linlin.shang@donders.ru.nl
avatar: ./assets/img/avatar.png
